-- Daily AI-generated recipes per user
-- This table stores AI-generated recipes that are personalized for each user
-- A new recipe is generated daily based on user's inventory, profile, and interests

create table if not exists public.daily_ai_recipes (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users (id) on delete cascade,
    title text not null,
    description text,
    ingredients jsonb not null default '[]'::jsonb,
    instructions jsonb not null default '[]'::jsonb,
    prep_time_minutes integer,
    cook_time_minutes integer,
    total_time_minutes integer not null,
    difficulty text check (difficulty in ('Makkelijk', 'Gemiddeld', 'Moeilijk')),
    servings integer,
    nutrition jsonb,
    tags text[],
    category text,
    image_url text,
    generated_at timestamptz not null default timezone('utc', now()),
    recipe_date date not null default current_date,
    created_at timestamptz not null default timezone('utc', now()),
    
    -- Ensure one recipe per user per day
    unique(user_id, recipe_date)
);

-- Index for fast lookups
create index if not exists daily_ai_recipes_user_date_idx 
    on public.daily_ai_recipes(user_id, recipe_date desc);

-- RLS Policies
alter table public.daily_ai_recipes enable row level security;

create policy "Users can view their own daily AI recipes"
    on public.daily_ai_recipes
    for select
    using (auth.uid() = user_id);

create policy "Users can insert their own daily AI recipes"
    on public.daily_ai_recipes
    for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own daily AI recipes"
    on public.daily_ai_recipes
    for update
    using (auth.uid() = user_id);

-- Function to get or generate today's AI recipe for a user
create or replace function get_daily_ai_recipe(p_user_id uuid)
returns public.daily_ai_recipes
language plpgsql
security definer
as $$
declare
    v_recipe public.daily_ai_recipes;
    v_today date := current_date;
begin
    -- Try to get today's recipe
    select * into v_recipe
    from public.daily_ai_recipes
    where user_id = p_user_id
      and recipe_date = v_today
    limit 1;
    
    -- Return if found
    if v_recipe is not null then
        return v_recipe;
    end if;
    
    -- If no recipe for today, return null (will be generated by the app)
    return null;
end;
$$;

-- Grant execute permission
grant execute on function get_daily_ai_recipe(uuid) to authenticated;

